CREATE TABLE IF NOT EXISTS ai_usage_requests (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(36) NOT NULL,
    sequence INTEGER NOT NULL,
    actor VARCHAR(64) NOT NULL,
    feature VARCHAR(48) NOT NULL,
    conversation_id INTEGER NULL,
    started_at DATETIME NOT NULL,
    model VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    http_status INTEGER NULL,
    error_code VARCHAR(80) NULL,
    provider_request_id VARCHAR(128) NULL,
    elapsed_ms INTEGER NULL,
    input_tokens INTEGER NULL,
    cached_tokens INTEGER NULL,
    output_tokens INTEGER NULL,
    reasoning_tokens INTEGER NULL,
    estimated_usd DECIMAL(16,8) NULL,
    estimated_usd_upper DECIMAL(16,8) NULL,
    pricing_version VARCHAR(64) NULL,
    sizes JSON NOT NULL,
    tools_used JSON NOT NULL,
    INDEX ix_ai_usage_requests_run_id (run_id),
    INDEX ix_ai_usage_requests_actor (actor),
    INDEX ix_ai_usage_requests_started_at (started_at)
);
